### ISSUE TITLE
did USING_STATIC_XERCES option used?

### ISSUE THREAD

**Issue by dogod621** [asmaloney/libE57Format#17]
Hi, no matter USING_STATIC_XERCES is set or not,
the compiled .exe still need xerces-c_3_2.dll...

or I am misunderstanding the option.. @@!!??

**Comment by asmaloney** [comment]
I'm not 100% sure since I don't compile on Windows, but I think you are :-) (I am using xerces-c from homebrew on macOS.)

The definition that gets added (`XERCES_STATIC_LIBRARY`) is from Xerces itself. The comment from there (_config.h.cmake.in_) is "Define if building a static library", so I am guessing it needs to be defined so that anything that uses it when it is statically built knows.

In your case, _if you are compiling Xerces as a static library_, then you need to define `USING_STATIC_XERCES` and (probably) add it to your target as well. Something like:

```cmake
set_property( TARGET <name> APPEND PROPERTY COMPILE_DEFINITIONS XERCES_STATIC_LIBRARY )
```

**Comment by asmaloney** [comment]
I still have no idea how the Xerces static vs. dynamic stuff works on Windows. If it is currently broken, please submit a [pull request](https://github.com/asmaloney/libE57Format/pulls) to fix it as I do not use this library on Windows.
